[profile.default]
src = "src"
out = "out"
libs = []
test = "test"
script = "script"
cache_path = "cache"
optimizer = true
optimizer_runs = 200
skip = [
    "src/lib/openzeppelin-contracts/test/**",
    "src/lib/openzeppelin-contracts/fv/**",
    "src/lib/openzeppelin-contracts/certora/**",
    "src/lib/openzeppelin-contracts/lib/**",
    "src/lib/openzeppelin-contracts/scripts/**"
]
remappings = [
    "forge-std/=src/lib/openzeppelin-contracts/lib/forge-std/src/",
    "@openzeppelin/=src/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts/=src/lib/openzeppelin-contracts/contracts/",
    "lib/solady/=lib/solady/"
]
